# Clone repositories into .helferlein directory
clone_directory: ".helferlein"
projects:
  helferlein:
    # Check for updates every 10 secnods
    fetch_interval: "10s"
    clone_url: "https://github.com/BrunoScheufler/helferlein.git"
    branches:
      main:
        steps:
          - echo "Hooray, changes! 🎉"
