# Fetch for updates every 10s
fetchInterval: "10s"
# Clone into .helferlein directory in current working directory
cloneDirectory: .helferlein
repositories:
  # Define "helferlein" repository to track
  - name: "helferlein"
    # Use GitHub https clone URL
    cloneUrl: "https://github.com/BrunoScheufler/helferlein.git"
    # Select "master" branch
    branches:
      # React to pushes to the master branch
      master:
        # Run the following commands in order
        steps:
          - echo "Hooray, we've got changes 🎉"
          - bash ./my-script.sh # commands are run in the cloned repository
